# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app
COPY requirements.txt .
# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Make port 9092 available to the world outside this container
EXPOSE 9092

# Define environment variable

# Run producer.py when the container launches
CMD ["python", "producer.py"]
