"""use single column for regions and lines and save color too

Revision ID: 34a3aae80c5c
Revises: bae66ce5e752
Create Date: 2024-03-15 21:21:40.715730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34a3aae80c5c'
down_revision = 'bae66ce5e752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('region_colors', sa.Text(), nullable=True))
        batch_op.drop_column('line_points')
        batch_op.drop_column('polygon_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polygon_points', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('line_points', mysql.TEXT(), nullable=True))
        batch_op.drop_column('region_colors')
        batch_op.drop_column('regions')

    # ### end Alembic commands ###
