"""Add new fields to Camera model

Revision ID: cf876c662946
Revises: 9eed47396ee1
Create Date: 2024-03-14 22:00:58.908720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf876c662946'
down_revision = '9eed47396ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('line_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('polygon_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('alert_emails', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('alert_emails')
        batch_op.drop_column('polygon_points')
        batch_op.drop_column('line_points')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
